### ISSUE TITLE
Sometimes unable to get track uri

### ISSUE THREAD

**Issue by Lahorde** [mopidy/mopidy-soundcloud#90] opened 2017-01-24 08:45 UTC
In some cases I have no issue with mopidy soundcloud. But sometimes, when i'm trying to play a soundlcloud track I have this exception :

```
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]: AttributeError: 'list' object has no attribute 'uri'
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]: WARNING  Track is not playable: soundcloud:song/Ghetto Paradise.30238568
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]: ERROR    SoundCloudBackend backend caused an exception.
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]: Traceback (most recent call last):
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:   File "/usr/lib/python2.7/site-packages/mopidy/core/playback.py", line 423, in _change
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:     if not backend.playback.change_track(pending_tl_track.track).get():
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:   File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:     exec('raise exc_info[0], exc_info[1], exc_info[2]')
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:     response = self._handle_receive(message)
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:     return callee(*message['args'], **message['kwargs'])
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:   File "/usr/lib/python2.7/site-packages/mopidy/backend.py", line 245, in change_track
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:     uri = self.translate_uri(track.uri)
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:   File "/usr/lib/python2.7/site-packages/mopidy_soundcloud/actor.py", line 35, in translate_uri
janv. 24 09:40:45 a4h-rpi-rel mopidy[15291]:     return track.uri
```

**Comment by caspargross** [comment] 2017-02-04 15:53
Same problem here.
```
    uri = self.translate_uri(track.uri)
  File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/actor.py", line 35, in translate_uri
    return track.uri
AttributeError: 'list' object has no attribute 'uri'
2017-02-04 16:47:03,670 WARNING [2432:Core-12] mopidy.core.tracklist: Track is not playable: soundcloud:song/Januarys New Moon Wartemal -Whats the Meaning of Life-.305075526
2017-02-04 16:47:10,249 INFO [2432:MpdSession-43] mopidy.mpd.session: New MPD connection from [::ffff:127.0.0.1]:38918
2017-02-04 16:47:10,432 INFO [2432:MpdSession-44] mopidy.mpd.session: New MPD connection from [::ffff:127.0.0.1]:38922
2017-02-04 16:47:14,729 INFO [2432:MpdSession-45] mopidy.mpd.session: New MPD connection from [::ffff:127.0.0.1]:38926
2017-02-04 16:47:24,782 INFO [2432:MpdSession-46] mopidy.mpd.session: New MPD connection from [::ffff:127.0.0.1]:38930
2017-02-04 16:47:30,209 INFO [2432:MpdSession-47] mopidy.mpd.session: New MPD connection from [::ffff:127.0.0.1]:38934
```

**Comment by Pixdigit** [comment] 2017-06-09 12:28
This is because self.backend.remote.get_track returns an empty list instead of None. I will look further into this but I give no guarantee that I will find the error.

**Comment by Pixdigit** [comment] 2017-06-09 13:53
Even though this repo is so easily maintainable I could not figure out what exactly happens. What I can say is that the error is caused by soundcloud.SoundCloudClient.parse_track returning an empty list when the returned json data by the soundcloud API does not include the keyword "streamable". However in actor.py it expects to either receive valid data or `None`. And since an empty list does not have a uri attribute it leads to the traceback above. However I could not figure out why _any_ songs on soundcloud are returned without streamable set to true. Even worse I somehow got a 401 response suddenly during testing. Maybe some DDoS protection by soundcloud? You can at least prevent it from crashing by changing
`if track is None:`
to 
`if track == []`.

This is quick and dirty but it stops error messages appearing.

**Comment by kingosticks** [comment] 2018-05-27 15:41
The error handling is improved in #100, I believe this is now fixed.

**Closed by kingosticks** 2018-05-27 15:41 UTC

**Comment by stekern** [comment] 2019-02-18 12:47
@kingosticks I started receiving the same error today. I've been using `mopidy-soundcloud` for months, and this is the first time I've encountered this issue. Searching on SoundCloud works fine, and I can add SoundCloud tracks to the tracklist. Playback, however, does not work.

Here is the track object I receive on my frontend:
```
{
  "track": {
    "album": {
      "images": [
        "https://i1.sndcdn.com/avatars-000312398765-riregv-large.jpg"
      ],
      "__model__": "Album",
      "name": "SoundCloud"
    },
    "comment": "https://soundcloud.com/earmilk/mac-miller-frick-park-market",
    "__model__": "Track",
    "name": "Mac Miller - Frick Park Market",
    "uri": "soundcloud:song/Mac Miller - Frick Park Market.21416472",
    "length": 196149,
    "artists": [
      {
        "__model__": "Artist",
        "name": "EARMILK"
      }
    ]
  },
  "__model__": "TlTrack",
  "tlid": 8
}
```
And here is the error on the backend:
```
mopidy_1    | INFO     'Mac Miller - Frick Park Market' can't be streamed from SoundCloud
mopidy_1    | ERROR    SoundCloudBackend backend caused an exception.
mopidy_1    | Traceback (most recent call last):
mopidy_1    |   File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playback.py", line 423, in _change
mopidy_1    |     if not backend.playback.change_track(pending_tl_track.track).get():
mopidy_1    |   File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
mopidy_1    |     compat.reraise(*self._data['exc_info'])
mopidy_1    |   File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
mopidy_1    |     exec('raise tp, value, tb')
mopidy_1    |   File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
mopidy_1    |     response = self._handle_receive(message)
mopidy_1    |   File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
mopidy_1    |     return callee(*message['args'], **message['kwargs'])
mopidy_1    |   File "/usr/local/lib/python2.7/dist-packages/mopidy/backend.py", line 245, in change_track
mopidy_1    |     uri = self.translate_uri(track.uri)
mopidy_1    |   File "/usr/lib/python2.7/dist-packages/mopidy_soundcloud/actor.py", line 35, in translate_uri
mopidy_1    |     return track.uri
mopidy_1    | AttributeError: 'list' object has no attribute 'uri'
mopidy_1    | WARNING  Track is not playable: soundcloud:song/Mac Miller - Frick Park Market.21416472
```

**Comment by kingosticks** [comment] 2019-02-18 15:59
Yeh, so it does seem the version from apt.mopidy.com is outdated, thanks for pointing that out. And you are right, we can't do anything about sharing the client_id. But the more people using v2.1.0 the better since that code is better optimised to use fewer credits. So let's see if we can get that sorted out.

**Comment by kingosticks** [comment] 2019-02-18 22:35
v2.1.0 is now available at apt.mopidy.com (thanks @jodal).
