### ISSUE TITLE
Authentication is broken

### ISSUE THREAD

**Issue by ibcht** [mopidy/mopidy-soundcloud#130] opened 2021-12-15 23:01 UTC
Hi,

I encountered the issue below : 

`ERROR    [SoundCloudBackend-9] mopidy_soundcloud.soundcloud Invalid "auth_token" used for SoundCloud authentication!`

After several attempts to reissue a token from the dedicated page https://mopidy.com/ext/soundcloud, I was still unable to process to the authentication step.

It looks like there has been some changes this year (around july apparently) on the authentication process to the SoundCloud API : https://developers.soundcloud.com/blog/security-updates-api. The Authorization Code flow with a direct token requested during the authorization step is now deprecated : 

> ### Changes in Authorization Code Flow
> For an authorization_code grant type, we’ll only support one response type: code. Token and **code_and_token** are deprecated and will be considered invalid.

Altought such tokens can still be issued, it looks like they are now unusable on the API unfortunately ...

Version tested : 3.0.1.

**Comment by kingosticks** [comment] 2021-12-15 23:07
Duplicate of https://github.com/mopidy/mopidy-soundcloud/issues/123

**Closed by kingosticks** 2021-12-15 23:07 UTC
